name: Spec (Runbook)
description: 流程规范 / 期望行为（长期维护）
title: "[Spec] "
labels:
  - type:spec
  - status:needs-triage
body:
  - type: input
    id: purpose
    attributes:
      label: Purpose
      description: 这份 Spec 的目的（一句话）
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope / Out of scope
      description: 适用范围与不适用范围
      placeholder: |
        适用：
        - daily 回归
        不适用：
        - 性能压测
    validations:
      required: true

  - type: textarea
    id: preconditions
    attributes:
      label: Preconditions
      description: 环境/权限/数据/服务依赖（Gate-Env）
    validations:
      required: true

  - type: textarea
    id: procedure
    attributes:
      label: Procedure (Gates)
      description: 步骤按 Gate 划分（Gate-Env / Gate-Run / Gate-Report / Gate-Judge）
      placeholder: |
        1) Gate-Env: ...
        2) Gate-Scope: ...
        3) Gate-Run: ...
        4) Gate-Report: ...
        5) Gate-Judge: ...
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Pass/Fail 判定 + 必须产物
    validations:
      required: true

  - type: textarea
    id: mapping
    attributes:
      label: Mapping (anchors)
      description: 必填：workflow 路径 + robot suite/tag + runner/入口
      placeholder: |
        workflows: workflows/xxx.yml
        robot tags: naohai_smoke, naohai_regression
        robot suites: tests/robot/naohai/...
        entry: python src/main_workflow.py ...
    validations:
      required: true

  - type: textarea
    id: change_policy
    attributes:
      label: Change Policy
      description: Spec 变更规则（必须写清）
      placeholder: |
        - Spec 变更必须经 Review（PR 或 Spec Issue 内记录）
        - 仅修 Bug 不改 Spec，除非预期行为变化
    validations:
      required: true